import type { Market, StockPrediction } from "@/lib/types";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { formatCurrency, getStockDetail, getStockPredictions } from "@/lib/api";

function formatDateLabel(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("en-US", { day: "2-digit", month: "short", year: "numeric" }).format(date);
}

function isFutureDate(value: string) {
  return value > new Date().toISOString().slice(0, 10);
}

export function PredictionBadgeSkeleton() {
  return (
    <Card className="animate-pulse bg-[var(--surface-strong)]">
      <CardHeader>
        <div className="h-4 w-40 rounded bg-[var(--surface-hover)]" />
      </CardHeader>
      <CardContent className="space-y-2">
        <div className="h-10 rounded-lg bg-[var(--surface-muted)]" />
        <div className="h-10 rounded-lg bg-[var(--surface-muted)]" />
        <div className="h-10 rounded-lg bg-[var(--surface-muted)]" />
      </CardContent>
    </Card>
  );
}

export async function PredictionBadge({
  ticker,
  market,
  predictions
}: {
  ticker: string;
  market: string;
  predictions?: StockPrediction[];
}) {
  try {
    const [detailResponse, predictionList] = await Promise.all([
      getStockDetail(ticker),
      predictions ?? getStockPredictions(ticker)
    ]);
    const currentPrice = detailResponse.price;
    const visiblePredictions = predictionList.filter((row) => isFutureDate(row.prediction_date));
    if (!visiblePredictions.length) return <UnavailableCard />;

    return (
      <Card className="bg-[var(--surface-strong)]">
        <CardHeader>
          <div className="flex items-center justify-between gap-3">
            <h2 className="text-sm font-semibold tracking-[0.2em] text-[#00d964]">PREDICTION</h2>
            <span className="text-xs text-[color:var(--text-faint)]">{market}</span>
          </div>
        </CardHeader>
        <CardContent className="space-y-2">
          {visiblePredictions.slice(0, 7).map((row) => {
            const bullish = row.predicted_price >= currentPrice;
            return (
              <div key={row.prediction_date} className="grid grid-cols-[1.1fr_1fr_1.2fr] gap-3 rounded-lg border border-[color:var(--border-color)] bg-[var(--surface-muted)] p-3 text-sm">
                <div className="text-[color:var(--text-secondary)]">{formatDateLabel(row.prediction_date)}</div>
                <div className={bullish ? "font-medium text-emerald-400" : "font-medium text-rose-400"}>{formatCurrency(row.predicted_price, market as Market, ticker)}</div>
                <div className="text-right text-[color:var(--text-muted)]">{formatCurrency(row.confidence_low, market as Market, ticker)} - {formatCurrency(row.confidence_high, market as Market, ticker)}</div>
              </div>
            );
          })}
          <p className="pt-1 text-xs leading-relaxed text-[color:var(--text-faint)]">
            Predictions are generated by Prophet model based on historical patterns. Not financial advice.
          </p>
        </CardContent>
      </Card>
    );
  } catch {
    return <UnavailableCard />;
  }
}

function UnavailableCard() {
  return <Card className="bg-[var(--surface-strong)]"><CardContent className="p-4 text-sm text-[color:var(--text-muted)]">Prediction not available</CardContent></Card>;
}
